### ISSUE TITLE
Content of index.xdk? / no logging

### ISSUE THREAD

**Issue by ElektrikTrick** [lg-lima1/xdk-datalogger#1]
Does the index.xdk need to contain any content or does it just need to be empty?
I just created any empty index.xdk file, datalogging doesn't work, no LED output.

Imported .zip-File into XDK-Workbench, builded and flashed the project on the xdk.

Any idea what I did wrong?

micro-sd is 32GB and formatted in FAT32.

**Comment by lg-lima1** [comment]
Missing this instruction in the readme, will improve that.

`index.xdk` is just a text file with a number. Please, modify the contents of your `index.xdk` with the number zero inside (no spaces, no line feed). It should look like this:

```
0
```

**Comment by ElektrikTrick** [comment]
Works! Thanks for helping!
